### ISSUE TITLE
fsevents fails in ubuntu

### ISSUE THREAD

**Issue by 3vivekb** [codeforsanjose/trash-pickup-portal#28]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

**Comment by 3vivekb** [comment]
Ubuntu npm log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle webpack-express-boilerplate@0.1.0~prestart: webpack-express-boilerplate@0.1.0
6 silly lifecycle webpack-express-boilerplate@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle webpack-express-boilerplate@0.1.0~start: webpack-express-boilerplate@0.1.0
8 verbose lifecycle webpack-express-boilerplate@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle webpack-express-boilerplate@0.1.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ubuntu/smelly-cat/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle webpack-express-boilerplate@0.1.0~start: CWD: /home/ubuntu/smelly-cat
11 silly lifecycle webpack-express-boilerplate@0.1.0~start: Args: [ '-c', 'node server' ]
12 info lifecycle webpack-express-boilerplate@0.1.0~start: Failed to exec start script
13 verbose stack Error: webpack-express-boilerplate@0.1.0 start: `node server`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid webpack-express-boilerplate@0.1.0
15 verbose cwd /home/ubuntu/smelly-cat
16 error Linux 4.4.0-47-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error webpack-express-boilerplate@0.1.0 start: `node server`
24 error spawn ENOENT
25 error Failed at the webpack-express-boilerplate@0.1.0 start script 'node server'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the webpack-express-boilerplate package,
25 error not with npm itself.

**Comment by 3vivekb** [comment]
Nevermind it works now.  Not sure why.
I ran:
sudo apt install nodejs-legacy
sudo npm install (again)
npm install
